version: '3'
services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - app-network

  node-app:
    image: nk:v1  
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=${PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
